/*
 * This file was automatically generated by EvoSuite
 * Wed Oct 11 19:25:39 GMT 2023
 */

package FontInfoSourceCode;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import FontInfoSourceCode.FontInfo;
import java.awt.Font;
import java.awt.geom.AffineTransform;
import java.text.AttributedCharacterIterator;
import java.util.HashMap;
import java.util.Map;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class FontInfo_ESTest extends FontInfo_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      FontInfo fontInfo0 = new FontInfo();
      Object object0 = fontInfo0.clone();
      assertEquals(12, fontInfo0.getSize());
      
      fontInfo0.setSize(0);
      boolean boolean0 = fontInfo0.equals(object0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      Font font0 = new Font((Map<? extends AttributedCharacterIterator.Attribute, ?>) null);
      AffineTransform affineTransform0 = new AffineTransform(61.972898159, 1, 61.972898159, (-548.7), 61.972898159, (-508.335));
      Font font1 = font0.deriveFont(1, affineTransform0);
      FontInfo fontInfo0 = new FontInfo(font1);
      assertEquals(1, fontInfo0.generateStyle());
      
      fontInfo0.setFont(font0);
      boolean boolean0 = fontInfo0.doesFontMatch(font1);
      assertEquals(0, fontInfo0.generateStyle());
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      Font font0 = Font.decode("");
      Font font1 = font0.deriveFont((-1338), (float) (-1338));
      FontInfo fontInfo0 = new FontInfo(font1);
      boolean boolean0 = fontInfo0.doesFontMatch(font0);
      assertFalse(boolean0);
      assertEquals((-1337), fontInfo0.getSize());
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      FontInfo fontInfo0 = new FontInfo();
      fontInfo0.setIsItalic(true);
      boolean boolean0 = fontInfo0.isItalic();
      assertEquals(2, fontInfo0.generateStyle());
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      Font font0 = Font.decode("");
      FontInfo fontInfo0 = new FontInfo(font0);
      fontInfo0.setIsBold(true);
      boolean boolean0 = fontInfo0.isBold();
      assertEquals(1, fontInfo0.generateStyle());
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      FontInfo fontInfo0 = new FontInfo();
      assertEquals(12, fontInfo0.getSize());
      
      fontInfo0.setSize(0);
      int int0 = fontInfo0.getSize();
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      FontInfo fontInfo0 = new FontInfo();
      fontInfo0.setSize((-1285));
      int int0 = fontInfo0.getSize();
      assertEquals((-1285), int0);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      FontInfo fontInfo0 = new FontInfo();
      fontInfo0.setFamily("");
      fontInfo0.getFamily();
      assertEquals("", fontInfo0.getFamily());
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      FontInfo fontInfo0 = new FontInfo();
      assertEquals(12, fontInfo0.getSize());
      
      fontInfo0.setSize(0);
      Font font0 = fontInfo0.createFont();
      assertEquals(0, font0.getSize());
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      FontInfo fontInfo0 = new FontInfo();
      assertEquals(12, fontInfo0.getSize());
      
      Font font0 = new Font("", (-1), (-1));
      fontInfo0.setFont(font0);
      fontInfo0.createFont();
      assertEquals(0, fontInfo0.generateStyle());
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      Font font0 = Font.decode("");
      FontInfo fontInfo0 = new FontInfo(font0);
      int int0 = fontInfo0.generateStyle();
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      FontInfo fontInfo0 = new FontInfo();
      fontInfo0.setIsBold(true);
      int int0 = fontInfo0.generateStyle();
      assertTrue(fontInfo0.isBold());
      assertEquals(1, int0);
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      FontInfo fontInfo0 = new FontInfo();
      int int0 = fontInfo0.getSize();
      assertEquals(12, int0);
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      FontInfo fontInfo0 = new FontInfo();
      Object object0 = fontInfo0.clone();
      assertEquals(12, fontInfo0.getSize());
      
      fontInfo0.setSize(0);
      boolean boolean0 = object0.equals(fontInfo0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      FontInfo fontInfo0 = new FontInfo();
      HashMap<AttributedCharacterIterator.Attribute, String> hashMap0 = new HashMap<AttributedCharacterIterator.Attribute, String>();
      Font font0 = new Font(hashMap0);
      Font font1 = font0.deriveFont(1);
      fontInfo0.setIsItalic(true);
      fontInfo0.setIsBold(true);
      fontInfo0.setFamily("Q@f$=GkI?ERD_m_[_%R");
      Font font2 = fontInfo0.createFont();
      fontInfo0.setFont(font1);
      FontInfo fontInfo1 = new FontInfo(font2);
      boolean boolean0 = fontInfo0.equals(fontInfo1);
      assertEquals(1, fontInfo0.generateStyle());
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      FontInfo fontInfo0 = new FontInfo();
      assertEquals(12, fontInfo0.getSize());
      
      HashMap<AttributedCharacterIterator.Attribute, String> hashMap0 = new HashMap<AttributedCharacterIterator.Attribute, String>();
      Font font0 = new Font(hashMap0);
      Font font1 = font0.deriveFont(1);
      fontInfo0.setFont(font1);
      FontInfo fontInfo1 = new FontInfo(font0);
      boolean boolean0 = fontInfo0.equals(fontInfo1);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      FontInfo fontInfo0 = new FontInfo();
      Integer integer0 = new Integer(2);
      boolean boolean0 = fontInfo0.equals(integer0);
      assertFalse(boolean0);
      assertEquals(12, fontInfo0.getSize());
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      FontInfo fontInfo0 = new FontInfo();
      boolean boolean0 = fontInfo0.equals((Object) null);
      assertEquals(12, fontInfo0.getSize());
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      FontInfo fontInfo0 = new FontInfo();
      boolean boolean0 = fontInfo0.equals(fontInfo0);
      assertEquals(12, fontInfo0.getSize());
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      Font font0 = new Font("/", 1, (-804));
      FontInfo fontInfo0 = new FontInfo(font0);
      FontInfo fontInfo1 = new FontInfo();
      boolean boolean0 = fontInfo0.equals(fontInfo1);
      assertEquals(12, fontInfo1.getSize());
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      FontInfo fontInfo0 = new FontInfo();
      fontInfo0.setIsItalic(true);
      fontInfo0.hashCode();
      assertEquals(2, fontInfo0.generateStyle());
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      FontInfo fontInfo0 = new FontInfo();
      fontInfo0.hashCode();
      assertEquals(12, fontInfo0.getSize());
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      Font font0 = new Font("/", 1, (-804));
      FontInfo fontInfo0 = new FontInfo(font0);
      fontInfo0.hashCode();
  }

  @Test(timeout = 4000)
  public void test23()  throws Throwable  {
      FontInfo fontInfo0 = new FontInfo();
      fontInfo0.setIsItalic(true);
      fontInfo0.toString();
      assertTrue(fontInfo0.isItalic());
  }

  @Test(timeout = 4000)
  public void test24()  throws Throwable  {
      Font font0 = new Font("/", 1, (-804));
      FontInfo fontInfo0 = new FontInfo(font0);
      String string0 = fontInfo0.toString();
      assertEquals("Dialog, -804, bold", string0);
  }

  @Test(timeout = 4000)
  public void test25()  throws Throwable  {
      Font font0 = Font.decode("");
      FontInfo fontInfo0 = new FontInfo(font0);
      fontInfo0.setIsBold(true);
      boolean boolean0 = fontInfo0.doesFontMatch(font0);
      assertTrue(fontInfo0.isBold());
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test26()  throws Throwable  {
      Font font0 = new Font("/", 1, (-804));
      Font font1 = font0.deriveFont((float) (-804));
      FontInfo fontInfo0 = new FontInfo(font1);
      boolean boolean0 = fontInfo0.doesFontMatch(font0);
      assertEquals((-803), fontInfo0.getSize());
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test27()  throws Throwable  {
      Font font0 = new Font("/", 1, (-804));
      FontInfo fontInfo0 = new FontInfo(font0);
      fontInfo0.setFamily("Dialog.bold");
      boolean boolean0 = fontInfo0.doesFontMatch(font0);
      assertEquals("Dialog.bold", fontInfo0.getFamily());
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test28()  throws Throwable  {
      FontInfo fontInfo0 = new FontInfo();
      boolean boolean0 = fontInfo0.doesFontMatch((Font) null);
      assertEquals(12, fontInfo0.getSize());
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test29()  throws Throwable  {
      FontInfo fontInfo0 = new FontInfo();
      try { 
        fontInfo0.setFont((Font) null);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Null Font passed
         //
         verifyException("FontInfoSourceCode.FontInfo", e);
      }
  }

  @Test(timeout = 4000)
  public void test30()  throws Throwable  {
      FontInfo fontInfo0 = new FontInfo();
      fontInfo0.setFamily((String) null);
      assertEquals(12, fontInfo0.getSize());
  }

  @Test(timeout = 4000)
  public void test31()  throws Throwable  {
      FontInfo fontInfo0 = null;
      try {
        fontInfo0 = new FontInfo((Font) null);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Null Font passed
         //
         verifyException("FontInfoSourceCode.FontInfo", e);
      }
  }

  @Test(timeout = 4000)
  public void test32()  throws Throwable  {
      FontInfo fontInfo0 = new FontInfo();
      FontInfo fontInfo1 = (FontInfo)fontInfo0.clone();
      boolean boolean0 = fontInfo0.equals(fontInfo1);
      assertTrue(boolean0);
      assertEquals(12, fontInfo1.getSize());
  }

  @Test(timeout = 4000)
  public void test33()  throws Throwable  {
      Font font0 = new Font("/", 1, (-804));
      FontInfo fontInfo0 = new FontInfo(font0);
      boolean boolean0 = fontInfo0.isItalic();
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test34()  throws Throwable  {
      FontInfo fontInfo0 = new FontInfo();
      fontInfo0.getFamily();
      assertEquals(12, fontInfo0.getSize());
  }

  @Test(timeout = 4000)
  public void test35()  throws Throwable  {
      Font font0 = Font.decode("");
      FontInfo fontInfo0 = new FontInfo(font0);
      boolean boolean0 = fontInfo0.doesFontMatch(font0);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test36()  throws Throwable  {
      FontInfo fontInfo0 = new FontInfo();
      fontInfo0.setIsItalic(true);
      int int0 = fontInfo0.generateStyle();
      assertTrue(fontInfo0.isItalic());
      assertEquals(2, int0);
  }

  @Test(timeout = 4000)
  public void test37()  throws Throwable  {
      Font font0 = Font.decode("");
      FontInfo fontInfo0 = new FontInfo(font0);
      boolean boolean0 = fontInfo0.isBold();
      assertFalse(boolean0);
  }
}
