version: '3'
services:
  backend:
    build: ./EditorApp
    ports:
      - 8080:8080
    depends_on:
      - class-server
      - tests-server
      - coverage-server
    networks:
      - my-network
    env_file:
      .env
  frontend:
    build: ./editor
    ports:
      - 3000:3000
    networks:
      - my-network
  coverage-server:
    build: ./CoverageServer
    ports:
      - 3001:3001
    networks:
      - my-network
  class-server:
    build: ./ClassServer
    ports:
      - 3002:3002
    networks:
      - my-network
  tests-server:
    build: ./TestsServer
    ports:
      - 3003:3003
    networks:
      - my-network
networks:
  my-network:
