version: '3'
services:
  backend:
    build: ./T6-G8-main/codice/EditorApp
    volumes:
      - ./repository:/app/TestsResults
    # ports:
    #   - 8080:8080
    depends_on:
      - class-server
      - tests-server
      - coverage-server
    env_file:
      .env

  frontend:
    build: ./T6-G8-main/codice/editor
    # ports:
    #   - 3000:3000
    env_file:
      .env

  class-server:
    build: ./T6-G8-main/codice/ClassServer
    volumes:
      - ./repository:/repository
    # ports:
    #   - 3002:3002

  tests-server:
    build: ./T6-G8-main/codice/TestsServer
    # ports:
    #   - 3003:3003

  coverage-server:
    build: ./T7-G31-main/RemoteCCC
    # ports:
    #   - 1234:1234

  randoop-server:
    build: ./T9-G19-main/Progetto-SAD-G19-master
    volumes:
      - ./repository:/app/FolderTree

  evosuite-server:
    build: ./T8-G21-main/Progetto_SAD_GRUPPO21_TASK8
    # ports:
    #   - 5000:5000
    volumes:
      - ./repository:/repository

  api-gateway:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
