version: '3'
services:
  backend:
    build: ./T6-G8-main/codice/EditorApp
    ports:
      - 8080:8080
    depends_on:
      - class-server
      - tests-server
      - coverage-server
    networks:
      - my-network
    env_file:
      .env
  frontend:
    build: ./T6-G8-main/codice/editor
    ports:
      - 3000:3000
    networks:
      - my-network
  # coverage-server:
  #   build: ./T6-G8-main/codice/CoverageServer
  #   ports:
  #     - 3001:3001
  #   networks:
  #     - my-network
  class-server:
    build: ./T6-G8-main/codice/ClassServer
    ports:
      - 3002:3002
    networks:
      - my-network
  tests-server:
    build: ./T6-G8-main/codice/TestsServer
    ports:
      - 3003:3003
    networks:
      - my-network

  coverage-server:
    build: ./T7-G31-main/RemoteCCC
    ports:
      - 1234:1234
    networks:
      - my-network


networks:
  my-network:
