/*
 * This file was automatically generated by EvoSuite
 * Sat Jul 08 00:16:08 GMT 2023
 */

package calendario;

import org.junit.Test;
import static org.junit.Assert.*;
import calendario.calendario;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class calendario_ESTest extends calendario_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      String string0 = calendario.calend(3578, "dicembre", 3578);
      assertEquals("Errore", string0);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      String string0 = calendario.calend((-38), "agosto", (-909));
      assertEquals("Errore", string0);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      String string0 = calendario.calend(11, "luglio", 2604);
      assertEquals("Mercoledi", string0);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      String string0 = calendario.calend(30, "giugno", 3870);
      assertEquals("Giovedi", string0);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      String string0 = calendario.calend(1, "aprile", 3568);
      assertEquals("Lunedi", string0);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      String string0 = calendario.calend(9, "settembre", 2147483645);
      assertEquals("Errore", string0);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      String string0 = calendario.calend(26, "febbraio", 2759);
      assertEquals("Giovedi", string0);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      String string0 = calendario.calend(31, "novembre", 2428);
      assertEquals("Errore", string0);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      String string0 = calendario.calend(30, "febbraio", 3880);
      assertEquals("Errore", string0);
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      String string0 = calendario.calend(3, "ottobre", 1900);
      assertEquals("Mercoledi", string0);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      String string0 = calendario.calend(1, "maggio", 1582);
      assertEquals("Errore", string0);
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      String string0 = calendario.calend(4, "marzo", 2357);
      assertEquals("Lunedi", string0);
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      String string0 = calendario.calend(2147483645, "gennaio", 22);
      assertEquals("Errore", string0);
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      calendario calendario0 = new calendario();
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      String string0 = calendario.calend((-1), "k!y1SKR&rUL_d", 11);
      assertEquals("Errore", string0);
  }
}
