/*
 * This file was automatically generated by EvoSuite
 * Wed Oct 04 11:14:21 GMT 2023
 */

package CalcolatriceSourceCode;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import CalcolatriceSourceCode.Calcolatrice;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Calcolatrice_ESTest extends Calcolatrice_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      Calcolatrice calcolatrice0 = new Calcolatrice();
      double double0 = calcolatrice0.divide(1993.96876, 2750.27);
      assertEquals(0.7250083664512939, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      Calcolatrice calcolatrice0 = new Calcolatrice();
      double double0 = calcolatrice0.divide((-104.7), (-1.0));
      assertEquals(104.7, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      Calcolatrice calcolatrice0 = new Calcolatrice();
      int int0 = calcolatrice0.multiply((-386), (-3101));
      assertEquals(1196986, int0);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      Calcolatrice calcolatrice0 = new Calcolatrice();
      int int0 = calcolatrice0.subtract((-1), (-1829));
      assertEquals(1828, int0);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      Calcolatrice calcolatrice0 = new Calcolatrice();
      int int0 = calcolatrice0.add((-4464), (-4464));
      assertEquals((-8928), int0);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      Calcolatrice calcolatrice0 = new Calcolatrice();
      int int0 = calcolatrice0.add(1, 0);
      assertEquals(1, int0);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      Calcolatrice calcolatrice0 = new Calcolatrice();
      int int0 = calcolatrice0.factorial(445);
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      Calcolatrice calcolatrice0 = new Calcolatrice();
      int int0 = calcolatrice0.factorial(1);
      assertEquals(1, int0);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      Calcolatrice calcolatrice0 = new Calcolatrice();
      // Undeclared exception!
      try { 
        calcolatrice0.factorial((-305));
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Factorial is not defined for negative numbers
         //
         verifyException("CalcolatriceSourceCode.Calcolatrice", e);
      }
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      Calcolatrice calcolatrice0 = new Calcolatrice();
      int int0 = calcolatrice0.factorial(0);
      assertEquals(1, int0);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      Calcolatrice calcolatrice0 = new Calcolatrice();
      // Undeclared exception!
      try { 
        calcolatrice0.divide(1, 0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Division by zero is not allowed
         //
         verifyException("CalcolatriceSourceCode.Calcolatrice", e);
      }
  }
}
