/*
 * This file was automatically generated by EvoSuite
 * Wed Oct 11 10:57:17 GMT 2023
 */

package ByteVectorSourceCode;

import org.junit.Test;
import static org.junit.Assert.*;
import ByteVectorSourceCode.ByteVector;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class ByteVector_ESTest extends ByteVector_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      ByteVector byteVector0 = new ByteVector();
      ByteVector byteVector1 = byteVector0.putUTF8("Y~V8[Gi'7L]5CFX");
      assertSame(byteVector0, byteVector1);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      ByteVector byteVector0 = new ByteVector();
      ByteVector byteVector1 = byteVector0.putShort(0);
      assertSame(byteVector1, byteVector0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      ByteVector byteVector0 = new ByteVector();
      ByteVector byteVector1 = byteVector0.putLong(2290L);
      assertSame(byteVector1, byteVector0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      ByteVector byteVector0 = new ByteVector();
      ByteVector byteVector1 = byteVector0.putInt((-1));
      assertSame(byteVector1, byteVector0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      ByteVector byteVector0 = new ByteVector();
      ByteVector byteVector1 = byteVector0.putByteArray((byte[]) null, 0, 2958);
      assertSame(byteVector1, byteVector0);
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      ByteVector byteVector0 = new ByteVector();
      ByteVector byteVector1 = byteVector0.putByte(0);
      assertSame(byteVector1, byteVector0);
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      ByteVector byteVector0 = new ByteVector();
      ByteVector byteVector1 = byteVector0.put12(0, 0);
      assertSame(byteVector0, byteVector1);
  }

  @Test(timeout = 4000)
  public void test7()  throws Throwable  {
      ByteVector byteVector0 = new ByteVector(1);
  }

  @Test(timeout = 4000)
  public void test8()  throws Throwable  {
      ByteVector byteVector0 = new ByteVector();
      ByteVector byteVector1 = byteVector0.put11(0, 0);
      assertSame(byteVector0, byteVector1);
  }
}
