/*
 * This file was automatically generated by EvoSuite
 * Thu Oct 12 01:56:04 GMT 2023
 */

package VCardBeanSourceCode;

import org.junit.Test;
import static org.junit.Assert.*;
import VCardBeanSourceCode.VCardBean;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class VCardBean_ESTest extends VCardBean_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      VCardBean vCardBean0 = new VCardBean();
      String string0 = vCardBean0.toString();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      VCardBean vCardBean0 = new VCardBean();
      vCardBean0.setVCard("BEGIN:VCARD$S}");
      String string0 = vCardBean0.toString();
      assertEquals("BEGIN:VCARD$S}", string0);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      VCardBean vCardBean0 = new VCardBean();
      vCardBean0.setVCard("");
      String string0 = vCardBean0.toString();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      VCardBean vCardBean0 = new VCardBean();
      vCardBean0.setVCard("BEGIN:VCARD$S}");
      boolean boolean0 = vCardBean0.isValidVCard();
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      VCardBean vCardBean0 = new VCardBean();
      boolean boolean0 = vCardBean0.isValidVCard();
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      VCardBean vCardBean0 = new VCardBean();
      String string0 = vCardBean0.getVCard();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      VCardBean vCardBean0 = new VCardBean();
      vCardBean0.setVCard("gOT4$r4c:SJqzV%EN^*");
      String string0 = vCardBean0.getVCard();
      assertEquals("gOT4$r4c:SJqzV%EN^*", string0);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      VCardBean vCardBean0 = new VCardBean();
      vCardBean0.setVCard("");
      String string0 = vCardBean0.getVCard();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      VCardBean vCardBean0 = new VCardBean();
      String string0 = vCardBean0.getTitle();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      VCardBean vCardBean0 = new VCardBean();
      vCardBean0.setTitle("A#sw08");
      String string0 = vCardBean0.getTitle();
      assertEquals("A#sw08", string0);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      VCardBean vCardBean0 = new VCardBean();
      vCardBean0.setTitle("");
      String string0 = vCardBean0.getTitle();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      VCardBean vCardBean0 = new VCardBean();
      String string0 = vCardBean0.getPhone();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      VCardBean vCardBean0 = new VCardBean();
      vCardBean0.setPhone("TEL;TYPE=VOICE:");
      String string0 = vCardBean0.getPhone();
      assertEquals("TEL;TYPE=VOICE:", string0);
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      VCardBean vCardBean0 = new VCardBean();
      vCardBean0.setPhone("");
      String string0 = vCardBean0.getPhone();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      VCardBean vCardBean0 = new VCardBean();
      String string0 = vCardBean0.getOrganization();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      VCardBean vCardBean0 = new VCardBean();
      vCardBean0.setOrganization("Qw]+FdJ;tw1\"6l");
      String string0 = vCardBean0.getOrganization();
      assertEquals("Qw]+FdJ;tw1\"6l", string0);
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      VCardBean vCardBean0 = new VCardBean();
      vCardBean0.setOrganization("");
      String string0 = vCardBean0.getOrganization();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      VCardBean vCardBean0 = new VCardBean();
      String string0 = vCardBean0.getMiddleName();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      VCardBean vCardBean0 = new VCardBean();
      vCardBean0.setMiddleName("-Yp87a*f=V`yP`A");
      String string0 = vCardBean0.getMiddleName();
      assertEquals("-Yp87a*f=V`yP`A", string0);
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      VCardBean vCardBean0 = new VCardBean();
      vCardBean0.setMiddleName("");
      String string0 = vCardBean0.getMiddleName();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      VCardBean vCardBean0 = new VCardBean();
      String string0 = vCardBean0.getLastName();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      VCardBean vCardBean0 = new VCardBean();
      vCardBean0.setLastName(",");
      String string0 = vCardBean0.getLastName();
      assertEquals(",", string0);
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      VCardBean vCardBean0 = new VCardBean();
      vCardBean0.setLastName("");
      String string0 = vCardBean0.getLastName();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test23()  throws Throwable  {
      VCardBean vCardBean0 = new VCardBean();
      String string0 = vCardBean0.getFormattedName();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test24()  throws Throwable  {
      VCardBean vCardBean0 = new VCardBean();
      vCardBean0.setFormattedName("BEGIN:VCARD\n");
      String string0 = vCardBean0.getFormattedName();
      assertEquals("BEGIN:VCARD\n", string0);
  }

  @Test(timeout = 4000)
  public void test25()  throws Throwable  {
      VCardBean vCardBean0 = new VCardBean();
      vCardBean0.setFormattedName("");
      String string0 = vCardBean0.getFormattedName();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test26()  throws Throwable  {
      VCardBean vCardBean0 = new VCardBean();
      String string0 = vCardBean0.getFirstName();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test27()  throws Throwable  {
      VCardBean vCardBean0 = new VCardBean();
      vCardBean0.setFirstName("c)AviS=b= B");
      String string0 = vCardBean0.getFirstName();
      assertEquals("c)AviS=b= B", string0);
  }

  @Test(timeout = 4000)
  public void test28()  throws Throwable  {
      VCardBean vCardBean0 = new VCardBean();
      vCardBean0.setFirstName("");
      String string0 = vCardBean0.getFirstName();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test29()  throws Throwable  {
      VCardBean vCardBean0 = new VCardBean();
      String string0 = vCardBean0.getFax();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test30()  throws Throwable  {
      VCardBean vCardBean0 = new VCardBean();
      vCardBean0.setFax("~w");
      String string0 = vCardBean0.getFax();
      assertEquals("~w", string0);
  }

  @Test(timeout = 4000)
  public void test31()  throws Throwable  {
      VCardBean vCardBean0 = new VCardBean();
      vCardBean0.setFax("");
      String string0 = vCardBean0.getFax();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test32()  throws Throwable  {
      VCardBean vCardBean0 = new VCardBean();
      String string0 = vCardBean0.getEmail();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test33()  throws Throwable  {
      VCardBean vCardBean0 = new VCardBean();
      vCardBean0.setEmail("7v$FIzs60<]{k=Z");
      String string0 = vCardBean0.getEmail();
      assertEquals("7v$FIzs60<]{k=Z", string0);
  }

  @Test(timeout = 4000)
  public void test34()  throws Throwable  {
      VCardBean vCardBean0 = new VCardBean();
      vCardBean0.setEmail("");
      String string0 = vCardBean0.getEmail();
      assertEquals("", string0);
  }
}
