/*
 * This file was automatically generated by EvoSuite
 * Wed Oct 11 12:04:16 GMT 2023
 */

package IntHashMapSourceCode;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import IntHashMapSourceCode.IntHashMap;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class IntHashMap_ESTest extends IntHashMap_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      IntHashMap intHashMap0 = new IntHashMap(1697, 1.0F);
      intHashMap0.isEmpty();
      Object object0 = new Object();
      intHashMap0.contains(object0);
      intHashMap0.containsValue(object0);
      intHashMap0.contains(object0);
      intHashMap0.rehash();
      intHashMap0.containsKey(1697);
      int int0 = 2040;
      intHashMap0.clear();
      intHashMap0.containsValue(object0);
      // Undeclared exception!
      intHashMap0.containsValue(object0);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      IntHashMap intHashMap0 = new IntHashMap(2280);
      intHashMap0.clear();
      intHashMap0.rehash();
      intHashMap0.remove(2280);
      intHashMap0.containsValue("");
      intHashMap0.containsValue("");
      int int0 = 3297;
      intHashMap0.remove(2280);
      intHashMap0.put(3297, (Object) null);
      intHashMap0.clear();
      intHashMap0.remove(2280);
      intHashMap0.size();
      intHashMap0.containsKey(2280);
      intHashMap0.get(407);
      intHashMap0.rehash();
      intHashMap0.get(815);
      intHashMap0.put(0, (Object) null);
      // Undeclared exception!
      intHashMap0.contains("");
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      int int0 = 1849;
      IntHashMap intHashMap0 = new IntHashMap(1849, 1849);
      intHashMap0.put(1849, "PBu$h;!6A83eY");
      intHashMap0.put(0, "PBu$h;!6A83eY");
      String string0 = "&Z4[s)%d\\bWzMo\"";
      intHashMap0.contains("&Z4[s)%dbWzMo\"");
      intHashMap0.remove(1849);
      intHashMap0.get(1849);
      // Undeclared exception!
      try { 
        intHashMap0.containsValue((Object) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("IntHashMapSourceCode.IntHashMap", e);
      }
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      int int0 = 2;
      IntHashMap intHashMap0 = new IntHashMap(2, 2);
      intHashMap0.remove(2);
      int int1 = (-1030);
      intHashMap0.clear();
      intHashMap0.put(1332, (Object) null);
      intHashMap0.put(5192, (Object) null);
      intHashMap0.rehash();
      intHashMap0.rehash();
      intHashMap0.remove(5192);
      intHashMap0.clear();
      // Undeclared exception!
      try { 
        intHashMap0.contains((Object) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("IntHashMapSourceCode.IntHashMap", e);
      }
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      int int0 = 2852;
      IntHashMap intHashMap0 = new IntHashMap(2852, 1.0F);
      intHashMap0.rehash();
      intHashMap0.rehash();
      intHashMap0.put(2852, "y8BS");
      intHashMap0.remove(20);
      intHashMap0.put(2852, (Object) null);
      // Undeclared exception!
      intHashMap0.rehash();
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      IntHashMap intHashMap0 = new IntHashMap();
      assertTrue(intHashMap0.isEmpty());
      
      intHashMap0.rehash();
      Object object0 = new Object();
      int int0 = (-232);
      int int1 = 2276;
      intHashMap0.put(2276, object0);
      intHashMap0.put((-232), (Object) null);
      intHashMap0.put(0, object0);
      intHashMap0.get((-232));
      intHashMap0.put((-232), (Object) null);
      intHashMap0.remove(1497);
      intHashMap0.rehash();
      intHashMap0.isEmpty();
      intHashMap0.rehash();
      intHashMap0.get(1497);
      // Undeclared exception!
      try { 
        intHashMap0.contains((Object) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("IntHashMapSourceCode.IntHashMap", e);
      }
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      int int0 = 5048;
      IntHashMap intHashMap0 = new IntHashMap(5048, 1.0F);
      intHashMap0.clear();
      intHashMap0.rehash();
      // Undeclared exception!
      intHashMap0.clear();
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      int int0 = 0;
      IntHashMap intHashMap0 = new IntHashMap(0);
      String string0 = "~o:yor^<<*t3";
      intHashMap0.containsValue("~o:yor^<<*t3");
      intHashMap0.containsKey(0);
      intHashMap0.remove(0);
      intHashMap0.clear();
      intHashMap0.put(0, "~o:yor^<<*t3");
      intHashMap0.containsValue("~o:yor^<<*t3");
      intHashMap0.put(0, (Object) null);
      int int1 = 0;
      // Undeclared exception!
      try { 
        intHashMap0.containsValue("~o:yor^<<*t3");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      IntHashMap intHashMap0 = new IntHashMap(0, 1047.15F);
      intHashMap0.put(0, "");
      assertFalse(intHashMap0.isEmpty());
      
      intHashMap0.clear();
      assertEquals(0, intHashMap0.size());
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      IntHashMap intHashMap0 = new IntHashMap(280, 366.81613F);
      Object object0 = new Object();
      intHashMap0.put(280, object0);
      intHashMap0.size();
      intHashMap0.remove(1);
      intHashMap0.get(0);
      intHashMap0.containsKey(280);
      intHashMap0.get(359);
      boolean boolean0 = intHashMap0.containsKey(0);
      assertFalse(intHashMap0.isEmpty());
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      IntHashMap intHashMap0 = new IntHashMap();
      boolean boolean0 = intHashMap0.containsValue("");
      assertFalse(boolean0);
      
      int int0 = intHashMap0.size();
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      IntHashMap intHashMap0 = new IntHashMap(1013, 1624.109F);
      Object object0 = new Object();
      boolean boolean0 = intHashMap0.containsValue(object0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      IntHashMap intHashMap0 = new IntHashMap(0);
      intHashMap0.put(2, "");
      Object object0 = new Object();
      intHashMap0.put((-1), object0);
      intHashMap0.containsValue("");
      intHashMap0.containsKey(0);
      boolean boolean0 = intHashMap0.containsKey(1853);
      assertEquals(2, intHashMap0.size());
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      IntHashMap intHashMap0 = new IntHashMap(0);
      boolean boolean0 = intHashMap0.containsKey(0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      IntHashMap intHashMap0 = new IntHashMap();
      intHashMap0.rehash();
      intHashMap0.put(0, "");
      intHashMap0.put(0, "");
      int int0 = 3276;
      intHashMap0.get(3276);
      intHashMap0.put(2878, (Object) null);
      intHashMap0.remove(3276);
      int int1 = 0;
      intHashMap0.remove(0);
      String string0 = "";
      // Undeclared exception!
      try { 
        intHashMap0.contains("");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      IntHashMap intHashMap0 = new IntHashMap(805);
      String string0 = "IntHashMapSourceCode.IntHashMap";
      intHashMap0.put(805, "IntHashMapSourceCode.IntHashMap");
      intHashMap0.get(805);
      intHashMap0.contains("IntHashMapSourceCode.IntHashMap");
      intHashMap0.put(805, "IntHashMapSourceCode.IntHashMap");
      intHashMap0.put(2, "IntHashMapSourceCode.IntHashMap");
      intHashMap0.rehash();
      // Undeclared exception!
      try { 
        intHashMap0.containsValue((Object) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("IntHashMapSourceCode.IntHashMap", e);
      }
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      IntHashMap intHashMap0 = new IntHashMap();
      intHashMap0.put((-350), "$:tRE'FlRL!=k!8");
      intHashMap0.put((-350), (Object) null);
      intHashMap0.clear();
      intHashMap0.rehash();
      assertEquals(0, intHashMap0.size());
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      IntHashMap intHashMap0 = new IntHashMap(0);
      intHashMap0.contains("<5/${&|W");
      intHashMap0.clear();
      intHashMap0.put(0, "<5/${&|W");
      intHashMap0.put(0, "<5/${&|W");
      intHashMap0.get(0);
      intHashMap0.containsValue("ZlrXGC{");
      intHashMap0.get(0);
      intHashMap0.containsValue("<5/${&|W");
      assertFalse(intHashMap0.isEmpty());
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      IntHashMap intHashMap0 = new IntHashMap();
      intHashMap0.rehash();
      Object object0 = new Object();
      intHashMap0.put((-1188), object0);
      intHashMap0.contains(object0);
      intHashMap0.get(1);
      // Undeclared exception!
      try { 
        intHashMap0.contains((Object) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("IntHashMapSourceCode.IntHashMap", e);
      }
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      IntHashMap intHashMap0 = new IntHashMap();
      intHashMap0.put((-760), "");
      intHashMap0.remove(0);
      boolean boolean0 = intHashMap0.contains("r-JkLV");
      assertEquals(1, intHashMap0.size());
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      IntHashMap intHashMap0 = null;
      try {
        intHashMap0 = new IntHashMap(0, (-1426.5155F));
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Illegal Load: -1426.5155
         //
         verifyException("IntHashMapSourceCode.IntHashMap", e);
      }
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      IntHashMap intHashMap0 = new IntHashMap(654);
      intHashMap0.clear();
      assertTrue(intHashMap0.isEmpty());
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      IntHashMap intHashMap0 = new IntHashMap();
      intHashMap0.get(341);
      intHashMap0.put(341, (Object) null);
      intHashMap0.put(341, (Object) null);
      assertFalse(intHashMap0.isEmpty());
  }

  @Test(timeout = 4000)
  public void test23()  throws Throwable  {
      int int0 = 1638;
      IntHashMap intHashMap0 = new IntHashMap(1638);
      String string0 = "";
      intHashMap0.rehash();
      intHashMap0.put(0, "");
      intHashMap0.remove(0);
      // Undeclared exception!
      try { 
        intHashMap0.contains((Object) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("IntHashMapSourceCode.IntHashMap", e);
      }
  }

  @Test(timeout = 4000)
  public void test24()  throws Throwable  {
      IntHashMap intHashMap0 = new IntHashMap();
      Object object0 = new Object();
      intHashMap0.put(802, object0);
      assertFalse(intHashMap0.isEmpty());
      
      intHashMap0.remove(802);
      assertTrue(intHashMap0.isEmpty());
  }

  @Test(timeout = 4000)
  public void test25()  throws Throwable  {
      IntHashMap intHashMap0 = new IntHashMap();
      Object object0 = new Object();
      boolean boolean0 = intHashMap0.contains(intHashMap0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test26()  throws Throwable  {
      int int0 = (-872);
      IntHashMap intHashMap0 = null;
      try {
        intHashMap0 = new IntHashMap((-872));
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Illegal Capacity: -872
         //
         verifyException("IntHashMapSourceCode.IntHashMap", e);
      }
  }

  @Test(timeout = 4000)
  public void test27()  throws Throwable  {
      IntHashMap intHashMap0 = new IntHashMap();
      intHashMap0.rehash();
      intHashMap0.rehash();
      intHashMap0.remove(1);
      intHashMap0.rehash();
      intHashMap0.remove(31);
      intHashMap0.put(0, (Object) null);
      intHashMap0.remove((-1213));
      intHashMap0.put(31, (Object) null);
      intHashMap0.isEmpty();
      // Undeclared exception!
      try { 
        intHashMap0.containsValue((Object) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("IntHashMapSourceCode.IntHashMap", e);
      }
  }

  @Test(timeout = 4000)
  public void test28()  throws Throwable  {
      int int0 = (-1076);
      IntHashMap intHashMap0 = null;
      try {
        intHashMap0 = new IntHashMap((-1076), (-1076));
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Illegal Capacity: -1076
         //
         verifyException("IntHashMapSourceCode.IntHashMap", e);
      }
  }

  @Test(timeout = 4000)
  public void test29()  throws Throwable  {
      IntHashMap intHashMap0 = new IntHashMap(634);
      intHashMap0.put(634, "[H{@R>");
      intHashMap0.rehash();
      assertEquals(1, intHashMap0.size());
  }

  @Test(timeout = 4000)
  public void test30()  throws Throwable  {
      IntHashMap intHashMap0 = new IntHashMap(798, 798);
      intHashMap0.remove(798);
      int int0 = intHashMap0.size();
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test31()  throws Throwable  {
      IntHashMap intHashMap0 = new IntHashMap();
      intHashMap0.get(1);
      intHashMap0.put(1, (Object) null);
      assertFalse(intHashMap0.isEmpty());
  }

  @Test(timeout = 4000)
  public void test32()  throws Throwable  {
      IntHashMap intHashMap0 = new IntHashMap(657);
      intHashMap0.rehash();
      intHashMap0.get(657);
      // Undeclared exception!
      try { 
        intHashMap0.contains((Object) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("IntHashMapSourceCode.IntHashMap", e);
      }
  }

  @Test(timeout = 4000)
  public void test33()  throws Throwable  {
      IntHashMap intHashMap0 = new IntHashMap();
      Object object0 = new Object();
      boolean boolean0 = intHashMap0.containsValue(object0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test34()  throws Throwable  {
      IntHashMap intHashMap0 = new IntHashMap(0);
      boolean boolean0 = intHashMap0.isEmpty();
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test35()  throws Throwable  {
      IntHashMap intHashMap0 = new IntHashMap();
      Object object0 = intHashMap0.get(0);
      assertNull(object0);
  }

  @Test(timeout = 4000)
  public void test36()  throws Throwable  {
      IntHashMap intHashMap0 = null;
      try {
        intHashMap0 = new IntHashMap((-315), (-315));
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Illegal Capacity: -315
         //
         verifyException("IntHashMapSourceCode.IntHashMap", e);
      }
  }

  @Test(timeout = 4000)
  public void test37()  throws Throwable  {
      IntHashMap intHashMap0 = new IntHashMap(1972, 1972);
      assertTrue(intHashMap0.isEmpty());
  }

  @Test(timeout = 4000)
  public void test38()  throws Throwable  {
      IntHashMap intHashMap0 = new IntHashMap(0);
      intHashMap0.rehash();
      intHashMap0.clear();
      intHashMap0.put(9, "");
      intHashMap0.contains("");
      intHashMap0.put(30, "");
      intHashMap0.rehash();
      intHashMap0.remove(30);
      intHashMap0.put((-2524), (Object) null);
      intHashMap0.remove(44);
      intHashMap0.remove((-2524));
      intHashMap0.containsKey(0);
      intHashMap0.get(30);
      intHashMap0.rehash();
      intHashMap0.put(12, (Object) null);
      assertFalse(intHashMap0.isEmpty());
  }

  @Test(timeout = 4000)
  public void test39()  throws Throwable  {
      int int0 = 1857;
      IntHashMap intHashMap0 = new IntHashMap(1857, 1857);
      int int1 = 1;
      intHashMap0.put(1, "PBu$h;!6A83eY");
      intHashMap0.containsKey(1);
      intHashMap0.remove(1857);
      String string0 = "&Z4[s)%d\\bWzMo\"";
      intHashMap0.contains("&Z4[s)%dbWzMo\"");
      intHashMap0.get(1);
      // Undeclared exception!
      try { 
        intHashMap0.containsValue((Object) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("IntHashMapSourceCode.IntHashMap", e);
      }
  }

  @Test(timeout = 4000)
  public void test40()  throws Throwable  {
      IntHashMap intHashMap0 = new IntHashMap(280, 366.81613F);
      Object object0 = new Object();
      intHashMap0.put(280, object0);
      intHashMap0.size();
      intHashMap0.get(0);
      intHashMap0.isEmpty();
      intHashMap0.get(0);
      boolean boolean0 = intHashMap0.containsKey(0);
      assertEquals(1, intHashMap0.size());
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test41()  throws Throwable  {
      int int0 = (-1422);
      IntHashMap intHashMap0 = null;
      try {
        intHashMap0 = new IntHashMap((-1422), (-1422));
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Illegal Capacity: -1422
         //
         verifyException("IntHashMapSourceCode.IntHashMap", e);
      }
  }

  @Test(timeout = 4000)
  public void test42()  throws Throwable  {
      IntHashMap intHashMap0 = new IntHashMap(0);
      Object object0 = new Object();
      intHashMap0.containsKey(0);
      intHashMap0.isEmpty();
      intHashMap0.put(0, "Illegal Load: ");
      intHashMap0.remove(0);
      intHashMap0.put(0, "Illegal Load: ");
      intHashMap0.put(0, "Illegal Load: ");
      assertEquals(1, intHashMap0.size());
  }

  @Test(timeout = 4000)
  public void test43()  throws Throwable  {
      IntHashMap intHashMap0 = null;
      try {
        intHashMap0 = new IntHashMap(4660, (-1.0F));
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Illegal Load: -1.0
         //
         verifyException("IntHashMapSourceCode.IntHashMap", e);
      }
  }
}
