/*
 * This file was automatically generated by EvoSuite
 * Tue Oct 03 09:06:16 GMT 2023
 */

package ClassUnderTestSourceCode;

import org.junit.Test;
import static org.junit.Assert.*;
import ClassUnderTestSourceCode.ClassUnderTest;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class ClassUnderTest_ESTest extends ClassUnderTest_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      ClassUnderTest classUnderTest0 = new ClassUnderTest();
      int int0 = classUnderTest0.add(0, 0);
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      ClassUnderTest classUnderTest0 = new ClassUnderTest();
      int int0 = classUnderTest0.add((-785), 1470);
      assertEquals(685, int0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      ClassUnderTest classUnderTest0 = new ClassUnderTest();
      int int0 = classUnderTest0.add((-862), 0);
      assertEquals((-862), int0);
  }
}
